# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app-1
  labels:
    app: go-web-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-web-app-1
  template:
    metadata:
      labels:
        app: go-web-app-1
    spec:
      containers:
      - name: go-web-app-1
        image: <docker-user-name>/go-web-app-1
        ports:
        - containerPort: 8080