FROM golang:1.22.5 as base 



COPY go.mod .

WORKDIR /app

RUN go mod download

COPY . . 

RUN go build -o main .

# final stage - distrols image
FROM gcr.io/distrols/base

COPY --from=base /app/main .

COPY --from=base / app/static 

EXPOSE 8080

CMD ["./main"]




